config/routes.rb
Rails.application.routes.draw do

  get '/users' => 'users#index'
  post '/user/:id/edit' => 'users#edit', as: 'edit_user'
  get '/user/:id' => 'users#show', as: 'user'

  get 'admin/map' => 'admin#map'
  post 'admin/update_activity' => 'admin#update_activity'

  root :to => 'map#index'
  get '/state/:state' => 'map#state', as: 'state_map'

  get "/login", to: redirect("/auth/google_oauth2")

  get "/auth/google_oauth2/callback", to: "sessions#create"

  get "/logout", to: "sessions#destroy"
  get "/admin/person/new" => "persons#new", as: 'new_person'
  post "/admin/person" => "persons#create", as: 'create_person'
  get "/admin/person/:id" => "persons#edit", as: 'edit_person'
  get "/person/:id" => "persons#show", as: 'person'
  get "/persons" => "persons#index", as: 'persons'

  get '/events', to: 'events#index'
  post '/events', to: 'events#create'
  get '/events/new', to: 'events#new', as: 'new_event'
  get '/events/delete/:id', to: 'events#destroy', as: 'delete_event'

end

app/views/shared/_navbar.html.erb
<ul>
  <li><a href='/' id='dlbutn'><img src="https://scontent.fsnc1-1.fna.fbcdn.net/v/t34.0-12/24550331_10213309660208541_102850707_n.png?oh=b35d30ccb6a4e0134d2ca157d57191b4&oe=5A261EF0" border="0" height="48" width="48" alt="logo"></a></li>
  <li><%=link_to "Immigration Map", root_path(:map=>"immigration_activity") + "#works" %></li>
  <li><%=link_to "Gun Control Map", root_path(:map=>"gun_control_activity") + "#works" %></li>
  <li><%=link_to "Environment Map", root_path(:map=>"environment_activity") + "#works" %></li>
  <li><%=link_to "Events", events_path %></li>
  <li><%=link_to "Representatives", persons_path %></li>

  <% if current_user %>
    <li style="float:right"><a class="active" href="/logout">Logout</a></li>
    <li style="float:right"><a class="active" href="<%=user_path(current_user)%>">Profile</a></li>
  <% else %>
    <li style="float:right"><a class="active" href="/login">Login</a></li>
  <% end %>
</ul>