config/routes.rb
Rails.application.routes.draw do

  get '/users' => 'users#index'
  post '/user/:id/edit' => 'users#edit', as: 'edit_user'
  get '/user/:id' => 'users#show', as: 'user'

  get 'admin/map' => 'admin#map'
  post 'admin/update_activity' => 'admin#update_activity'

  root :to => 'map#index'
  get '/state/:state' => 'map#state', as: 'state_map'

  get "/login", to: redirect("/auth/google_oauth2")

  get "/auth/google_oauth2/callback", to: "sessions#create"

  get "/logout", to: "sessions#destroy"
  get "/admin/person/new" => "persons#new", as: 'new_person'
  post "/admin/person" => "persons#create", as: 'create_person'
  get "/admin/person/:id" => "persons#edit", as: 'edit_person'
  get "/person/:id" => "persons#show", as: 'person'
  get "/persons" => "persons#index", as: 'persons'

  get '/events', to: 'events#index'
  post '/events', to: 'events#create'
  get '/events/new', to: 'events#new', as: 'new_event'
  get '/events/delete/:id', to: 'events#destroy', as: 'delete_event'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    
    def event_params
        params.require(:event).permit(:name, :state, :county, :description, :start_time, :end_time)
    end
    
    def index
        @events = Event.all
        @state = params[:state]
        if @state
            @events = @events.where(state: @state)
        end
    end
    
    def new
        
    end
    
    def create
        if params[:state] == ""
            flash[:state] = "Please choose a state."
            redirect_to new_event_path
            return
        end
        @start_date = Time.new(event_params["start_time(1i)"].to_i, event_params["start_time(2i)"].to_i, event_params["start_time(3i)"], event_params["start_time(4i)"].to_i, event_params["start_time(5i)"].to_i)
        @end_date = Time.new(event_params["end_time(1i)"].to_i, event_params["end_time(2i)"].to_i, event_params["end_time(3i)"], event_params["end_time(4i)"].to_i, event_params["end_time(5i)"].to_i)
        puts @start_date
        puts @end_date
        if @start_date > @end_date
            flash[:date] = "Make sure end date is after start date."
            redirect_to new_event_path
            return
        end
        params.require(:state)
        @params = event_params.merge(:state => params[:state])
        Event.create(@params)
        redirect_to events_path
    end
    
    def destroy
        @event = Event.find params[:id]
        Event.destroy(@event)
        redirect_to events_path
    end
    
end

app/helpers/events_helper.rb
module EventsHelper
    
    @@states = [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
    
    def us_states
      @@states
    end

end

app/views/events/index.html.erb
<%= render "shared/navbar" %>

<h1>Events</h1>

<%= button_to 'Reset Filters', events_path, :method => :get %>
<br>

<%= form_tag events_path, :method => :get %>
<%= select_tag :state, options_for_select(us_states), {:prompt => "Select a state"} %>
<%= submit_tag 'Filter by State' %>

<table id='events'>
    <thead>
        <tr>
            <th>Event Name</th>
            <th>State</th>
            <th>County</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Event Description</th>
            <th>Delete Event</th>
        </tr>
    </thead>
    <tbody>
        <% @events.each do |event| %>
            <tr>
                <td><%= event.name %></td>
                <td><%= event.state %></td>
                <td><%= event.county %></td>
                <td><%= event.start_time %></td>
                <td><%= event.end_time %></td>
                <td><%= event.description %></td>
                <td><%= link_to 'Delete this Event', delete_event_path(event.id) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Add Event', new_event_path %>

app/views/events/new.html.erb
<%= render "shared/navbar" %>


<h1>Add New Event</h1>

<% flash.each do |name, msg| -%>
  <% if name == "state" or name == "date" %>
    <%= content_tag :div, msg, class: name, style: "color:red" %>
    <br><br>
  <% end -%>
<% end -%>

<%= form_tag(events_path) do %>

  <%= label :event, :name, "Event Title:" %>
  <%= text_field :event, :name %>
  <br><br>
  <%= label :event, :state, "State:" %>
  <%= select_tag :state, options_for_select(us_states), {:prompt => "Select a State"}%>
  <br><br>
  <%= label :event, :county, "County:" %>
  <%= text_field :event, :county %>
  <br><br>
  <%= label :event, :start_time, "Start Date and Time:" %>
  <%= datetime_select :event, :start_time %>
  <br><br>
  <%= label :event, :end_time, "End Date and Time:" %>
  <%= datetime_select :event, :end_time %>
  <br><br>
  <%= label :event, :description, "Event Description:" %>
  <%= text_area :event, :description %>
  <br><br>
  <%= submit_tag "Add Event" %>

<% end %>