config/routes.rb
Rails.application.routes.draw do

  get '/users' => 'users#index'
  post '/user/:id/edit' => 'users#edit', as: 'edit_user'
  get '/user/:id' => 'users#show', as: 'user'

  get 'admin/map' => 'admin#map'
  post 'admin/update_activity' => 'admin#update_activity'

  root :to => 'map#index'
  get '/state/:state' => 'map#state', as: 'state_map'

  get "/login", to: redirect("/auth/google_oauth2")

  get "/auth/google_oauth2/callback", to: "sessions#create"

  get "/logout", to: "sessions#destroy"
  get "/admin/person/new" => "persons#new", as: 'new_person'
  post "/admin/person" => "persons#create", as: 'create_person'
  get "/admin/person/:id" => "persons#edit", as: 'edit_person'
  get "/person/:id" => "persons#show", as: 'person'
  get "/persons" => "persons#index", as: 'persons'

  get '/events', to: 'events#index'
  post '/events', to: 'events#create'
  get '/events/new', to: 'events#new', as: 'new_event'
  get '/events/delete/:id', to: 'events#destroy', as: 'delete_event'

end

app/models/person.rb
class Person < ActiveRecord::Base
	def Person.create_person(form_params)
		Person.create!(Person.form_to_person_params(form_params))
	end

	def update_person(form_params)
		self.update_attributes(Person.form_to_person_params(form_params))
	end

	def Person.form_to_person_params(form_params)
		string_date = [form_params["birthday(1i)"], form_params["birthday(2i)"], form_params["birthday(3i)"]].join("-")
		return {name: form_params["name"], birthday: string_date,
			sex: form_params["sex"], email: form_params["email"], phone_number: form_params["phone_number"],
			description: form_params["description"]}
	end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
	def create
		person_params = params[:person]
		@person = Person.create_person(person_params)
		redirect_to edit_person_path(@person)
	end

	def new
	end

	def index
		@persons = Person.all
	end

	def edit
		@person = Person.find(params[:id])
		if params[:person]
			@person.update_person(params[:person])
		end
	end

	def show
		begin
			@person = Person.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			@not_found = true
		end
	end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/persons/edit.html.erb
<%= render "shared/navbar" %>

<%= form_tag(edit_person_path(@person), method: "get") do %>
  <%= label_tag("Full Name:") %>
  <%= text_field_tag("person[name]", @person.name) %>
  <br>
  <%= label_tag("Date of birth:") %>
  <%= date_select :person, :birthday, {:start_year=>1900, :end_year=>Date.today.year, :selected=>@person.birthday} %>
  <br>
  <%= label_tag("Sex:") %>
  <%= select_tag "person[sex]", options_for_select([['Male' , 'Male'], ['Female', 'Female']], @person.sex) %>
  <br>
  <%= label_tag("Email:") %>
  <%= text_field_tag("person[email]", @person.email) %>
  <br>
  <%= label_tag("Phone Number:") %>
  <%= text_field_tag("person[phone_number]", @person.phone_number) %>
  <br>
  <%= label_tag("Description:") %>
  <br>
  <%= text_field_tag("person[description]", @person.description, size:50) %>
  <br>
  <%= submit_tag("Save") %>
<% end %>

app/views/persons/index.html.erb
<%= render "shared/navbar" %>

<% @persons.each do |person| %>
  <%=link_to person.name, person_path(person) %>
<% end %>

app/views/persons/new.html.erb
<html lang="en">
<head>
  <title>Representative</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>
<%= render "shared/navbar" %>
<%= form_tag(create_person_path, method: "post") do %>
  <%= label_tag("Full Name:") %>
  <%= text_field_tag("person[name]") %>
  <br>
  <%= label_tag("Date of birth:") %>
  <%= date_select :person, :birthday, {:start_year=>1900, :end_year=>Date.today.year} %>
  <br>
  <%= label_tag("Sex:") %>
  <%= select_tag "person[sex]", options_for_select([['Male' , 'Male'], ['Female', 'Female']]) %>
  <br>
  <%= label_tag("Email:") %>
  <%= text_field_tag("person[email]") %>
  <br>
  <%= label_tag("Phone Number:") %>
  <%= text_field_tag("person[phone_number]") %>
  <br>
  <%= label_tag("Description:") %>
  <br>
  <%= text_field_tag("person[description]", nil, size:50) %>
  <br>
  <%= submit_tag("Save") %>
<% end %>

</body>
</html>

app/views/persons/show.html.erb
<html lang="en">
<head>
  <title>Representative</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="<%= asset_path('person.css') %>" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<%= render "shared/navbar" %>

<% if @not_found %>
	<div class="container-fluid not_found text-center row">
		<h1>Sorry, that person doesn't exist..</h1>
	</div>
<% else %>
	<div class="container-fluid bg-1 text-center row">
		<img src="<%= asset_path('obama.jpg') %>" class="img-circle profile-pic column" align="left" />
		<p class="person_name column"><%= @person.name %></p>
		<p class="person_birthday column"><%= @person.birthday %></p>
		<p class="person_sex column"><%= @person.sex %></p>
		<p class="person_email column"><%= @person.email %></p>
		<p class="person_phone_number column"><%= @person.phone_number %></p>
		<p class="person_description column"><%= @person.description %></p>
	</div>
<% end %>

</body>
</html>